### ISSUE TITLE
服务器相关issue

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_server#3]
今天凌晨1点多开始貌似就没有广播了，只有连接公告

**Comment by lzghzr** [comment]
自己搭建的吗？
目前发现的bug确实会导致断线以后无法自动重连(因为没有心跳超时)，ws这个库的作者也倾向于自己写ping超时的逻辑，近期会修复
________________________________

**Comment by Vector000** [comment]
不，是你提供的那个
然后我就自己搭了个，然后连不上
![default](https://user-images.githubusercontent.com/33326900/48299627-aaa25880-e50a-11e8-9577-7d58bfceec7d.PNG)

**Comment by lzghzr** [comment]
我还真没注意，因为对外提供的是个转发服务器，可能存在断开不重连的bug
________________________________

**Comment by lzghzr** [comment]
增加了超时重连，这回应该没问题了

**Comment by ShmilyChen** [comment]
每一次Auto-commit之后都需要git pull吗？

**Comment by lzghzr** [comment]
不需要，只是自动push了一下数据库

2018年11月17日 12:03，ShmilyChen <notifications@github.com>写道：

每一次Auto-commit之后都需要git pull吗？

―

**Comment by ShmilyChen** [comment]
好的，谢谢
