### ISSUE TITLE
服务器连接bug

### ISSUE THREAD

**Issue by Vector000** [lzghzr/bilive_server#4]
在同一主机上部署bilive_client和bilive_server，bilive_server新建一用户组，在bilive_client中连接`wss://localhost:20080/#protocol`会触发
![image](https://user-images.githubusercontent.com/33326900/48300823-99634700-e51e-11e8-8e32-bd594db118c7.png)

**Comment by lzghzr** [comment]
wss是websocket over tls
你localhost没有有效证书当然不行

**Comment by lzghzr** [comment]
本地搭建用`ws://`就行

**Comment by Vector000** [comment]
刚意识到这问题，在搞
